export type BlogPost = {
  slug: string;
  title: string;
  desc: string;
  icon: string;
  toolHref: string;
  toolName: string;
  body: string[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "emi-calculator-guide",
    title: "EMI Calculator — complete guide",
    desc: "Loan EMI kaise nikalte hain, formula aur practical tips.",
    icon: "🏦",
    toolHref: "/emi",
    toolName: "EMI Calculator",
    body: [
      "EMI (Equated Monthly Installment) woh fixed monthly payment hai jo aap loan pe adaa karte ho. Isme principal aur interest dono shamil hote hain.",
      "EMI isliye important hai ke aap budget clear rakh sako: har mahine kitna kate ga, total interest kitna padega, aur tenure badhne se kya farq padta hai.",
      "Standard formula mein monthly rate annual rate se banta hai, aur tenure months mein convert hota hai. Zero interest edge case mein EMI seedha principal ÷ months hoti hai.",
      "Practical tip: tenure badhao to monthly EMI kam dikhti hai, lekin total interest aksar badh jata hai. Pehle affordable EMI dekho, phir total cost compare karo.",
      "CalcKit ka EMI tool live results deta hai — slider se amount, rate aur years change karte hi chart aur numbers update ho jate hain.",
    ],
  },
  {
    slug: "sip-vs-lumpsum",
    title: "SIP vs Lumpsum — simple comparison",
    desc: "Kab SIP behtar hai aur kab one-time investment.",
    icon: "📈",
    toolHref: "/sip",
    toolName: "SIP Calculator",
    body: [
      "SIP mein aap fixed amount regularly invest karte ho. Lumpsum mein poori raqam ek saath lagti hai.",
      "SIP ka faida discipline aur averaging hai: market up-down dono phases mein units accumulate hote rehte hain.",
      "Lumpsum tab socha jata hai jab badi raqam ready ho aur aap long horizon pe comfortable ho. Short-term volatility zyada mehsoos ho sakti hai.",
      "Koi bhi projected return guarantee nahi hota. Calculator assumed rate se estimate deta hai — real mutual fund returns vary karte hain.",
      "CalcKit SIP calculator se maturity value, total invested aur estimated gain turant dekh sakte ho.",
    ],
  },
  {
    slug: "bmi-kya-hota-hai",
    title: "BMI kya hota hai?",
    desc: "Body Mass Index categories aur healthy range ki simple explanation.",
    icon: "⚖️",
    toolHref: "/bmi",
    toolName: "BMI Calculator",
    body: [
      "BMI weight aur height se nikla screening number hai. Yeh body fat directly measure nahi karta, lekin population level pe categories define karta hai.",
      "Common adult bands: under 18.5 underweight, 18.5–24.9 normal, 25–29.9 overweight, 30+ obese.",
      "Athletes ya high muscle mass wale logon ka BMI misleading ho sakta hai. Is liye medical decisions sirf BMI pe mat lo.",
      "CalcKit BMI tool live gauge ke sath category dikhata hai — weight/height change karte hi result update hota hai.",
    ],
  },
  {
    slug: "age-calculator-kaise-kaam-karta-hai",
    title: "Age Calculator kaise kaam karta hai",
    desc: "Date of birth se exact years, months aur days.",
    icon: "🎂",
    toolHref: "/age",
    toolName: "Age Calculator",
    body: [
      "Age calculator aaj ki date aur date of birth ke beech calendar difference nikalta hai.",
      "Pehle years, phir months, phir days adjust kiye jate hain taake negative values na aayein.",
      "Total days lived alag se day-count se aata hai — leap years calendar ke hisaab se count hote hain.",
      "Forms, exams aur eligibility checks ke liye exact age kaafi useful hoti hai. Device ki local date 'aaj' decide karti hai.",
    ],
  },
  {
    slug: "compound-interest-explained",
    title: "Compound interest explained simply",
    desc: "Interest on interest — savings growth ka asli engine.",
    icon: "💹",
    toolHref: "/compound",
    toolName: "Compound Interest Calculator",
    body: [
      "Simple interest sirf original principal pe lagta hai. Compound interest pehle ke interest pe bhi interest jodta hai.",
      "Frequency matter karti hai: monthly compounding quarterly se alag path de sakti hai same annual rate pe.",
      "Regular deposits (SIP-style) ke sath future value aur bhi tezi se badh sakti hai kyunki har deposit bhi compound hota hai.",
      "CalcKit compound tool principal, deposit, rate, years aur frequency ke sath live projection deta hai.",
    ],
  },
  {
    slug: "simple-interest-basics",
    title: "Simple interest basics",
    desc: "P × R × T / 100 — short-term interest ka seedha hisaab.",
    icon: "💰",
    toolHref: "/simple-interest",
    toolName: "Simple Interest Calculator",
    body: [
      "Simple interest formula school se familiar hai: Interest = Principal × Rate × Time / 100.",
      "Yeh short-term loans ya teaching examples mein common hai. Zyada modern products compound models use karte hain.",
      "Total amount = principal + interest. Rate annual assume hoti hai jab tak explicitly na kaha jaye.",
      "CalcKit pe values change karte hi interest aur total live update hota hai.",
    ],
  },
  {
    slug: "cagr-meaning",
    title: "CAGR ka matlab kya hai?",
    desc: "Compound annual growth rate se multi-year growth samjho.",
    icon: "📊",
    toolHref: "/cagr",
    toolName: "CAGR Calculator",
    body: [
      "CAGR woh steady annual rate hai jo beginning value ko ending value tak le jaye, given years mein.",
      "Yeh volatility hide karta hai: actual saal-ba-saal returns up-down ho sakte hain, CAGR smoothed picture hai.",
      "Investments compare karte waqt CAGR useful hai, lekin risk aur drawdowns alag se dekho.",
      "CalcKit CAGR tool start, end aur years se percentage turant nikalta hai.",
    ],
  },
  {
    slug: "roi-calculator-guide",
    title: "ROI calculator guide",
    desc: "Return on investment — profit ko invested amount se compare karo.",
    icon: "🎯",
    toolHref: "/roi",
    toolName: "ROI Calculator",
    body: [
      "ROI = (Returned − Invested) / Invested × 100. Yeh batata hai ke capital pe kitna percent faida ya nuqsan hua.",
      "Basic ROI time ignore karta hai: 10% in 1 year aur 10% in 5 years same ROI number de sakte hain.",
      "Time-aware comparison ke liye CAGR ya annualized metrics better hote hain.",
      "CalcKit ROI tool profit aur percentage live dikhata hai.",
    ],
  },
  {
    slug: "inflation-and-purchasing-power",
    title: "Inflation aur purchasing power",
    desc: "Aaj ki raqam future mein kitni 'kamzor' ho sakti hai.",
    icon: "📉",
    toolHref: "/inflation",
    toolName: "Inflation Calculator",
    body: [
      "Inflation prices badhane se same money se kam cheezein milti hain — purchasing power girti hai.",
      "Future nominal amount ≈ present × (1 + rate)^years. Yeh planning assumption hai, guarantee nahi.",
      "Long-term goals (education, retirement) set karte waqt inflation buffer rakhna sensible hai.",
      "CalcKit inflation calculator se assumed rate pe future value estimate karo.",
    ],
  },
  {
    slug: "percentage-calculator-tips",
    title: "Percentage calculator tips",
    desc: "X% of Y, percent of, aur percent change — teen common sawal.",
    icon: "%",
    toolHref: "/percentage",
    toolName: "Percentage Calculator",
    body: [
      "Discounts, marks, growth reports — har jagah percentages aate hain.",
      "Teen modes: X% of Y; X is what % of Y; percent change from X to Y.",
      "Percent change aur percentage points alag cheezein hain: 10% se 12% = 2 points, lekin 20% relative change.",
      "CalcKit percentage tool teeno modes live support karta hai.",
    ],
  },
  {
    slug: "tax-add-or-extract",
    title: "Tax add karna ya extract karna",
    desc: "Net price vs tax-inclusive price — clear breakdown.",
    icon: "🧾",
    toolHref: "/tax",
    toolName: "Tax Calculator",
    body: [
      "Kabhi tax net amount pe add hota hai, kabhi quoted price pehle se tax-inclusive hoti hai.",
      "Add mode: tax = amount × rate/100. Extract mode: net = inclusive ÷ (1 + rate/100).",
      "Yeh generic calculator hai — official GST/VAT rules, exemptions aur rounding jurisdiction ke mutabiq hon.",
      "CalcKit tax tool dono modes mein live net, tax aur total dikhata hai.",
    ],
  },
  {
    slug: "discount-sale-price",
    title: "Discount se sale price kaise nikalein",
    desc: "Percent off ke baad final payable amount.",
    icon: "🏷️",
    toolHref: "/discount",
    toolName: "Discount Calculator",
    body: [
      "Sale tags aksar “20% off” likhte hain. Final price = original − (original × percent/100).",
      "Ek se zyada sequential discounts alag-alag steps mein apply hote hain; single percent tool ek step karta hai.",
      "Budget shopping se pehle save amount dekhna useful hota hai.",
      "CalcKit discount calculator final price aur savings live update karta hai.",
    ],
  },
  {
    slug: "currency-converter-live-rates",
    title: "Currency converter aur live rates",
    desc: "Mid-market rate vs bank rate — farq kyun hota hai.",
    icon: "💱",
    toolHref: "/currency",
    toolName: "Currency Converter",
    body: [
      "Online converters aksar mid-market reference rate use karte hain. Banks spread aur fees add karte hain.",
      "Is liye app/bank quote calculator se thoda alag ho sakta hai — normal baat hai.",
      "Live conversion ke liye internet zaroori hai. Offline pe rates refresh nahi honge.",
      "CalcKit currency tool amount aur pair change karte hi estimate refresh karta hai.",
    ],
  },
  {
    slug: "unit-conversion-basics",
    title: "Unit conversion basics",
    desc: "Length, weight, temperature — common conversions.",
    icon: "📐",
    toolHref: "/unit",
    toolName: "Unit Converter",
    body: [
      "Recipes, travel, science homework — units convert karna roz marra ka kaam hai.",
      "Length/weight fixed factors se convert hote hain. Temperature °C/°F/K formulas use karti hai.",
      "1 m ≈ 3.2808 ft, 0°C = 32°F — yeh common references yaad rakhne layak hain.",
      "CalcKit unit converter type select karke live result dikhata hai.",
    ],
  },
  {
    slug: "gpa-4-point-scale",
    title: "GPA on a 4.0 scale",
    desc: "Credits aur grade points se weighted average.",
    icon: "🎓",
    toolHref: "/gpa",
    toolName: "GPA Calculator",
    body: [
      "GPA = total grade points ÷ total credits. Higher credit course average pe zyada asar dalta hai.",
      "Har university ka letter-to-point map thoda alag ho sakta hai (A+, A−, etc.).",
      "Semester planning mein “what-if” grades se target GPA set karna useful hai.",
      "CalcKit GPA tool courses add karke 4.0 scale pe estimate deta hai.",
    ],
  },
  {
    slug: "loan-amortization-schedule",
    title: "Loan amortization schedule samjho",
    desc: "Har EMI mein principal vs interest ka breakdown.",
    icon: "📋",
    toolHref: "/amortization",
    toolName: "Amortization Calculator",
    body: [
      "Amortization table batati hai ke har mahine kitna interest aur kitna principal kata.",
      "Shuru ke payments mein interest hissa bada hota hai; aakhir mein principal zyada kata hai.",
      "Extra principal payment strategies samajhne ke liye schedule dekhna helpful hai.",
      "CalcKit amortization tool EMI ke sath month-by-month table generate karta hai.",
    ],
  },
  {
    slug: "credit-card-payoff-tips",
    title: "Credit card payoff tips",
    desc: "High interest pe balance kab clear hoga.",
    icon: "💳",
    toolHref: "/credit-card",
    toolName: "Credit Card Payoff",
    body: [
      "Credit cards pe annual rates high ho sakti hain. Agar payment sirf interest cover kare to balance stuck reh sakta hai.",
      "Fixed monthly payment se months-to-payoff aur total interest estimate kiya ja sakta hai.",
      "Pehle high-rate balances clear karna aksar total cost kam karta hai (avalanche approach).",
      "CalcKit payoff calculator unrealistic low payments pe clearly bata deta hai ke debt shrink nahi hogi.",
    ],
  },
  {
    slug: "savings-goal-planning",
    title: "Savings goal planning",
    desc: "Target amount ke liye monthly saving kitni chahiye.",
    icon: "🎯",
    toolHref: "/savings-goal",
    toolName: "Savings Goal Calculator",
    body: [
      "Goal-based saving clear target se start hoti hai: amount, timeline, expected return, current savings.",
      "Zyada time ya better assumed return monthly burden kam kar sakta hai — lekin returns guaranteed nahi.",
      "Emergency fund aur short goals ke liye conservative rate assumptions better hote hain.",
      "CalcKit savings goal tool required monthly amount live nikalta hai.",
    ],
  },
  {
    slug: "margin-vs-markup",
    title: "Margin vs markup",
    desc: "Profit ko price se dekho ya cost se — dono alag hain.",
    icon: "📦",
    toolHref: "/margin",
    toolName: "Margin Calculator",
    body: [
      "Margin = profit ÷ selling price. Markup = profit ÷ cost. Numbers alag aate hain same deal pe.",
      "Retail conversations mein “margin” aksar price pe based hoti hai; purchasing teams markup sochti hain.",
      "Confusion se pricing mistakes hoti hain — dono metrics clearly label karo.",
      "CalcKit margin tool profit, margin% aur markup% ek saath dikhata hai.",
    ],
  },
  {
    slug: "breakeven-point-business",
    title: "Break-even point for small business",
    desc: "Kitni units becho ke fixed costs cover ho jayein.",
    icon: "⚖️",
    toolHref: "/breakeven",
    toolName: "Break-even Calculator",
    body: [
      "Break-even units = fixed costs ÷ (price − variable cost per unit).",
      "Agar price variable cost se kam/equal ho to contribution zero — break-even impossible.",
      "Pricing, cost cuts, ya volume targets set karte waqt yeh pehli checkpoint hai.",
      "CalcKit break-even calculator units aur revenue live estimate karta hai.",
    ],
  },
  {
    slug: "present-value-future-value",
    title: "Present value aur future value",
    desc: "Time value of money — aaj vs kal ki raqam.",
    icon: "🔮",
    toolHref: "/pv-fv",
    toolName: "PV / FV Calculator",
    body: [
      "Future value aaj ki raqam ko rate se aage badhati hai. Present value future raqam ko aaj discount karti hai.",
      "FV = PV × (1+r)^n. PV = FV ÷ (1+r)^n. Simple annual model planning ke liye clear hai.",
      "Insurance targets, education corpus, deferred payments — PV/FV intuition kaam aati hai.",
      "CalcKit PV/FV tool mode switch ke sath live result deta hai.",
    ],
  },
  {
    slug: "date-difference-calculator",
    title: "Date difference calculator",
    desc: "Do dates ke beech din, hafte, mahine.",
    icon: "📅",
    toolHref: "/date",
    toolName: "Date Difference",
    body: [
      "Project deadlines, tenancy periods, course durations — date spans roz kaam aate hain.",
      "Exact days calendar se milte hain. Months/years averages approximate hote hain kyunki months ki length vary karti hai.",
      "Legal deadlines ke liye hamesha exact day count prefer karo.",
      "CalcKit date tool dono dates select karte hi span dikhata hai.",
    ],
  },
  {
    slug: "basic-calculator-everyday",
    title: "Basic calculator for everyday math",
    desc: "Quick arithmetic without phone clutter.",
    icon: "∑",
    toolHref: "/basic",
    toolName: "Basic Calculator",
    body: [
      "Kabhi-kabhi sirf fast + − × ÷ chahiye hota hai — basic calculator wahi karta hai.",
      "Browser mein open rakho, mobile-friendly keypad se roz marra ke hisaab lagao.",
      "Finance, units, ya BMI ke liye specialized CalcKit tools better hain; basic math yahin.",
    ],
  },
];

export function getPost(slug: string) {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
